.TH "Hash-it" "1" "" "Version 0.1.2" "Hash-it Manual Page Documentation"
.SH NAME
com.github.libredeb.hashit \- The most intuitive and simple
hash tool checker for elementary OS
.SH SYNOPSIS
.PP
\f[B]com.github.libredeb.hashit\f[R] [ OPTION ] \&...
.SH DESCRIPTION
Hashit is a fast and beautiful hash check tool.
Writen in Vala and GTK+ 4.0 with the purpose to get the hash of file and compare it with other provided hash.
.SH Options
.TP
\-h, \[en]-help
Show help options.
.TP
\--help-all
Show all help options.
.TP
\--help-gapplication
Show GApplication options.
.SH FILES
.SH AUTHOR
Juan Pablo Lozano \c
.MT libredeb@gmail.com
.ME \c